### ISSUE TITLE
Надо колонку как мы решили

### ISSUE THREAD

**Issue by slavacestmoi** [karpoftea/mts-kata-2023#14]
В вопросах надо колонку "как мы решили, предположили", где нет ответа, или заказчик сказал самим додумать

**Comment by karpoftea** [comment]
Сделаем какой-нить раздел "Допущения"

**Comment by slavacestmoi** [comment]
Тогда надо вопросы нумеровать

**Comment by karpoftea** [comment]
Я сделал в вопросах колонку учтен ли он в требованиях. Если вопрос учтен значит появилось по нему ФТ/НФТ, а у них есть номер. Если допущение будет снимать ФТ/НФТ, то сошлемся. Но могут и не снимать - по некоторым вещам у нас просто не будет инфы и мы сделаем допущение.
